// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRgISnmp7zR0hoxTBkvwShLDEE1_oZs9I',
    appId: '1:1035539627021:web:8c4fa0743346e6ecb7a944',
    messagingSenderId: '1035539627021',
    projectId: 'baycel-grocery-store',
    authDomain: 'baycel-grocery-store.firebaseapp.com',
    storageBucket: 'baycel-grocery-store.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB0ybHN6qL4uuaNvazZ_vhsEhumV0MknA',
    appId: '1:1035539627021:android:c4175d5c2bf1b7dfb7a944',
    messagingSenderId: '1035539627021',
    projectId: 'baycel-grocery-store',
    storageBucket: 'baycel-grocery-store.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQU3oyzqTJUfMSI-9eptc6Ycg9uGV5io',
    appId: '1:1035539627021:ios:06b7dca0315979f5b7a944',
    messagingSenderId: '1035539627021',
    projectId: 'baycel-grocery-store',
    storageBucket: 'baycel-grocery-store.firebasestorage.app',
    iosBundleId: 'com.example.baycelGrocery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRgISnmp7zR0hoxTBkvwShLDEE1_oZs9I',
    appId: '1:1035539627021:web:769da1c41c0e20e7b7a944',
    messagingSenderId: '1035539627021',
    projectId: 'baycel-grocery-store',
    authDomain: 'baycel-grocery-store.firebaseapp.com',
    storageBucket: 'baycel-grocery-store.firebasestorage.app',
  );
}
